---

tunnel_proxy_image_prefix: ghcr.io/stackhpc
tunnel_proxy_image_name: tunnel-client
tunnel_proxy_image_tag: main
tunnel_proxy_image: "{{ tunnel_proxy_image_prefix }}/{{ tunnel_proxy_image_name }}:{{ tunnel_proxy_image_tag }}"
tunnel_proxy_image_pull: yes

tunnel_proxy_sshd_host: c1102a29.nip.io
tunnel_proxy_sshd_port: "32222"
