---

- name: Start tunnel proxy
  docker_container:
    name: "{{ tunnel_proxy_name }}"
    image: "{{ tunnel_proxy_image }}"
    pull: "{{ tunnel_proxy_image_pull }}"
    container_default_behavior: no_defaults
    detach: yes
    restart_policy: unless-stopped
    network_mode: "{{ tunnel_proxy_docker_net }}"
    networks:
      - name: "{{ tunnel_proxy_docker_net }}"
    networks_cli_compatible: yes
    env: "{{ tunnel_proxy_environment }}"
    state: started
