
---
#####
## Tasks to set up the SSH connection for guacamole
#####

- name: Ensure guacamole SSH directory exists
  file:
    path: /etc/guacamole/ssh-auth
    state: directory

# Generate an RSA keypair for guacamole to use to authenticate with the host
# At the time of writing, Guacamole does not support new-style OpenSSH keys
#   See: https://issues.apache.org/jira/browse/GUACAMOLE-745
#
# Also, at the time of writing the community.crypto.openssh_keypair module has
# a parameter called private_key_format but the only valid value is "auto"
# which uses the default OpenSSH format
#
# So we have to use ssh-keygen directly to generate the keypair in PEM format
- name: Generate SSH keypair for local SSH auth
  command: >
    ssh-keygen
      -m PEM -t rsa -b 3072 -N ""
      -C guacamole-auth
      -f /etc/guacamole/ssh-auth/{{ guacamole_user }}
  args:
    creates: /etc/guacamole/ssh-auth/{{ guacamole_user }}

- name: Slurp SSH private key from file
  slurp:
    src: /etc/guacamole/ssh-auth/{{ guacamole_user }}
  register: guacamole_private_key_file

- name: Slurp SSH public key from file
  slurp:
    src: /etc/guacamole/ssh-auth/{{ guacamole_user }}.pub
  register: guacamole_public_key_file

- name: Set SSH keypair facts
  set_fact:
    guacamole_ssh_private_key: "{{ guacamole_private_key_file.content | b64decode }}"
    guacamole_ssh_public_key: "{{ guacamole_public_key_file.content | b64decode }}"

- name: Write SSH public key to authorized keys for guacamole SSH user
  authorized_key:
    user: "{{ guacamole_user }}"
    state: present
    key: "{{ guacamole_ssh_public_key }}"
