---

guacamole_image_prefix: guacamole

guacamole_version: 1.3.0

guacamole_server_image_name: guacd
guacamole_server_image_tag: "{{ guacamole_version }}"
guacamole_server_image: "{{ guacamole_image_prefix }}/{{ guacamole_server_image_name }}:{{ guacamole_server_image_tag }}"
guacamole_server_image_pull: no

guacamole_client_image_name: guacamole
guacamole_client_image_tag: "{{ guacamole_version }}"
guacamole_client_image: "{{ guacamole_image_prefix }}/{{ guacamole_client_image_name }}:{{ guacamole_client_image_tag }}"
guacamole_client_image_pull: no

guacamole_user: centos

_openstack_metadata: "{{ lookup('url', 'http://169.254.169.254/openstack/latest/meta_data.json') | from_json }}"

# Determine whether to enable the desktop from the instance metadata
guacamole_desktop_enabled: "{{ (_openstack_metadata.meta.portal_desktop_enabled | default('0') == '1' }}"

# TODO: PULL THIS FROM INSTANCE METADATA
guacamole_password_hash: "{{ 'portal' | hash('md5') }}"
