---

- name: Install Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Python Docker bindings
  pip:
    name: docker
    state: present

- name: Refresh network facts to pick up Docker bridge
  setup:
    gather_subset: network
  when: "'docker0' not in ansible_interfaces"
