---

- name: Install Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
    state: present

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

# We do this using the command module as making pip reliably install into the
# Ansible Python interpreter is not trivial
# We have to specify six explicitly until this issue is fixed in a released version
# https://github.com/docker/docker-py/issues/2842
- name: Install Python Docker bindings
  command: "{{ ansible_python_interpreter }} -m pip install docker six"

- name: Refresh network facts to pick up Docker bridge
  setup:
    gather_subset: network
  when: "'docker0' not in ansible_interfaces"
